/**
 * Renders the app icons from one SVG source.
 *
 * The only mark the project had was a 64x64 webp, which cannot be upscaled to
 * the 512 a PWA install needs. Drawing it as vector means the icon set is
 * reproducible and stays in step with the palette.
 *
 * Run with: npm run icons
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import opentype from "opentype.js";
import sharp from "sharp";

const OUT = join(process.cwd(), "public", "icons");
// Next serves these two by file convention, which is what replaces
// the old favicon.ico.
const APP = join(process.cwd(), "src", "app");

const BRAND = "#0F766E";
const ON_BRAND = "#FFFFFF";

/** The dial position the mark freezes at: 5h45 of a 12-hour face. */
const SWEEP = (5.75 / 12) * 360;

/**
 * The two faces the app uses, pinned to the exact files Google serves today.
 *
 * They are downloaded into a cache the repository ignores rather than
 * committed, because what this script produces — a PNG — is the thing worth
 * versioning. The renderer never sees them as fonts: text is converted to
 * outlines below, since librsvg, which sharp rasterises with, ignores an
 * embedded @font-face and would silently substitute whatever the machine
 * happens to have. A card that looks different on every machine is worse than
 * no card.
 */
const FONTS = {
  display: {
    file: "BricolageGrotesque-ExtraBold.ttf",
    url: "https://fonts.gstatic.com/s/bricolagegrotesque/v9/3y9U6as8bTXq_nANBjzKo3IeZx8z6up5BeSl5jBNz_19PpbpMXuECpwUxJBOm_OJWiaaD30YfKfjZZoLvZvlyM0.ttf",
  },
  body: {
    file: "PublicSans-Regular.ttf",
    url: "https://fonts.gstatic.com/s/publicsans/v21/ijwGs572Xtc6ZYQws9YVwllKVG8qX1oyOymuFpm5ww.ttf",
  },
};

const FONT_CACHE = join(process.cwd(), "scripts", ".fonts");

async function loadFont({ file, url }) {
  const path = join(FONT_CACHE, file);

  if (!existsSync(path)) {
    console.log("downloading", file);
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(
        `Could not download ${file} (HTTP ${response.status}). The card is ` +
          `only regenerated by hand, so this needs a connection — or drop ` +
          `the file into scripts/.fonts/ yourself.`
      );
    }
    await mkdir(FONT_CACHE, { recursive: true });
    await writeFile(path, Buffer.from(await response.arrayBuffer()));
  }

  const buffer = await readFile(path);
  return opentype.parse(
    buffer.buffer.slice(
      buffer.byteOffset,
      buffer.byteOffset + buffer.byteLength
    )
  );
}

/**
 * Walks a string glyph by glyph, applying kerning by hand.
 *
 * opentype.js's own getPath and getAdvanceWidth run the string through a
 * shaping engine that throws on this font's ccmp lookup ("Lookup type is not
 * yet supported"). Nothing here needs shaping — two short Latin lines with no
 * ligatures — so going straight to the glyphs avoids the whole path.
 */
function layout(font, text, size) {
  const scale = size / font.unitsPerEm;
  const glyphs = [];
  let width = 0;
  let previous = null;

  for (const character of text) {
    const glyph = font.charToGlyph(character);
    if (previous !== null)
      width += font.getKerningValue(previous, glyph) * scale;
    glyphs.push({ glyph, offset: width });
    width += glyph.advanceWidth * scale;
    previous = glyph;
  }

  return { glyphs, width };
}

/**
 * One line of text as outlines, so no font has to exist at render time.
 *
 * One <path> per glyph, not one for the whole line: librsvg stops reading a
 * `d` attribute somewhere past four thousand characters, which silently drew
 * the first eight letters of the tagline and dropped the rest. Per glyph, no
 * line comes anywhere near the limit.
 */
function textPath(font, text, x, y, size, fill, opacity = 1) {
  const { glyphs } = layout(font, text, size);
  const fillOpacity = opacity === 1 ? "" : ` fill-opacity="${opacity}"`;

  return glyphs
    .map(({ glyph, offset }) =>
      glyph.getPath(x + offset, y, size).toPathData(2)
    )
    .filter((d) => d.length > 0)
    .map((d) => `<path d="${d}" fill="${fill}"${fillOpacity}/>`)
    .join("");
}

const textWidth = (font, text, size) => layout(font, text, size).width;

/**
 * A clock ring with the worked part of a shift drawn over it. The default
 * journey is 5h45 of a 12-hour dial, which is the arc below.
 */
function mark({ size = 512, inset = 1, rounded = true }) {
  const c = size / 2;
  const radius = size * 0.293 * inset;
  const stroke = size * 0.055 * inset;
  const dot = size * 0.052 * inset;

  const sweep = SWEEP;
  const point = (deg) => {
    const rad = ((deg - 90) * Math.PI) / 180;
    return [c + radius * Math.cos(rad), c + radius * Math.sin(rad)];
  };
  const [x0, y0] = point(0);
  const [x1, y1] = point(sweep);
  const largeArc = sweep > 180 ? 1 : 0;

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
  <rect width="${size}" height="${size}"${rounded ? ` rx="${size * 0.22}"` : ""} fill="${BRAND}"/>
  <circle cx="${c}" cy="${c}" r="${radius}" fill="none" stroke="${ON_BRAND}" stroke-opacity="0.3" stroke-width="${stroke}"/>
  <path d="M ${x0.toFixed(2)} ${y0.toFixed(2)} A ${radius.toFixed(2)} ${radius.toFixed(2)} 0 ${largeArc} 1 ${x1.toFixed(2)} ${y1.toFixed(2)}"
        fill="none" stroke="${ON_BRAND}" stroke-width="${stroke}" stroke-linecap="round"/>
  <circle cx="${x1.toFixed(2)}" cy="${y1.toFixed(2)}" r="${dot}" fill="${ON_BRAND}"/>
</svg>`;
}

const TARGETS = [
  { file: "icon.svg", svg: mark({}) },
  { file: "icon-192.png", size: 192, svg: mark({}) },
  { file: "icon-512.png", size: 512, svg: mark({}) },
  // Maskable icons are cropped to a circle by some launchers, so the glyph
  // sits inside the 80% safe zone and the ground bleeds to the edges.
  {
    file: "icon-maskable-512.png",
    size: 512,
    svg: mark({ inset: 0.72, rounded: false }),
  },
  { file: "apple-touch-icon.png", size: 180, svg: mark({ rounded: false }) },
];

await mkdir(OUT, { recursive: true });

for (const target of TARGETS) {
  const path = join(OUT, target.file);
  if (target.file.endsWith(".svg")) {
    await writeFile(path, target.svg, "utf8");
  } else {
    await sharp(Buffer.from(target.svg)).resize(target.size).png().toFile(path);
  }
  console.log("wrote", target.file);
}

/**
 * The card that stands in for the app when a link is shared.
 *
 * Drawn rather than screenshotted: a screenshot goes stale with every layout
 * change, and the one it replaced still showed the 2023 interface, a version
 * number two majors old, and a menu that no longer exists.
 *
 * 1200x630 is what LinkedIn, WhatsApp and Slack all read. Note that their
 * caches are aggressive — the first fetch after publishing is effectively the
 * one that sticks.
 */
async function ogCard() {
  const [display, body] = await Promise.all([
    loadFont(FONTS.display),
    loadFont(FONTS.body),
  ]);

  const W = 1200;
  const H = 630;
  const X = 96;
  // The text column stops here so it never runs into the mark on the right.
  const COLUMN = 700;

  const title = "REP Calc";
  const tagline = "Calculadora de horas para quem bate ponto";
  const url = "repcalc.leandrofaria.com";

  const titleSize = 116;
  const taglineSize = 34;
  const urlSize = 26;

  // Better to fail here than to ship a card with a word running under the
  // mark. The sizes above are chosen against this, not the other way round.
  const widest = Math.max(
    textWidth(display, title, titleSize),
    textWidth(body, tagline, taglineSize)
  );
  if (widest > COLUMN) {
    throw new Error(
      `Text overflows the column: ${Math.round(widest)}px of ${COLUMN}px.`
    );
  }

  // The app's own mark, at card scale. Same geometry as the icons, so the
  // thing someone sees in a link preview is the thing on their home screen.
  const cx = 960;
  const cy = H / 2;
  // Literally the icon's proportions, read off the same ratios mark() uses,
  // so the thing in a link preview is the thing on the home screen.
  const nominal = 512;
  const radius = nominal * 0.293;
  const stroke = nominal * 0.055;
  const point = (deg) => {
    const rad = ((deg - 90) * Math.PI) / 180;
    return [cx + radius * Math.cos(rad), cy + radius * Math.sin(rad)];
  };
  const [x0, y0] = point(0);
  const [x1, y1] = point(SWEEP);

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
  <rect width="${W}" height="${H}" fill="${BRAND}"/>
  <circle cx="${cx}" cy="${cy}" r="${radius}" fill="none" stroke="${ON_BRAND}" stroke-opacity="0.3" stroke-width="${stroke}"/>
  <path d="M ${x0.toFixed(2)} ${y0.toFixed(2)} A ${radius} ${radius} 0 ${SWEEP > 180 ? 1 : 0} 1 ${x1.toFixed(2)} ${y1.toFixed(2)}"
        fill="none" stroke="${ON_BRAND}" stroke-width="${stroke}" stroke-linecap="round"/>
  <circle cx="${x1.toFixed(2)}" cy="${y1.toFixed(2)}" r="${nominal * 0.052}" fill="${ON_BRAND}"/>
  ${textPath(display, title, X, 322, titleSize, ON_BRAND)}
  ${textPath(body, tagline, X, 382, taglineSize, ON_BRAND, 0.9)}
  ${textPath(body, url, X, 520, urlSize, ON_BRAND, 0.6)}
</svg>`;
}

await sharp(Buffer.from(await ogCard()))
  .png({ compressionLevel: 9 })
  .toFile(join(process.cwd(), "public", "og.png"));
console.log("wrote public/og.png");

// The browser tab icon and the iOS home-screen icon, by Next's file
// convention. Same source, so they cannot drift from the palette.
await writeFile(join(APP, "icon.svg"), mark({}), "utf8");
await sharp(Buffer.from(mark({ rounded: false })))
  .resize(180)
  .png()
  .toFile(join(APP, "apple-icon.png"));
console.log("wrote src/app/icon.svg and src/app/apple-icon.png");
