/**
 * Renders the app icons from one SVG source.
 *
 * The only mark the project had was a 64x64 webp, which cannot be upscaled to
 * the 512 a PWA install needs. Drawing it as vector means the icon set is
 * reproducible and stays in step with the palette.
 *
 * Run with: npm run icons
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import opentype from "opentype.js";
import sharp from "sharp";
import {
  MARK,
  MARK_COLORS,
  arcPath,
  haloInnerRadius,
  haloOuterRadius,
} from "../src/lib/design/mark.mjs";

const OUT = join(process.cwd(), "public", "icons");
// Next serves these two by file convention, which is what replaces
// the old favicon.ico.
const APP = join(process.cwd(), "src", "app");

const ON_BRAND = "#FFFFFF";

/**
 * The ground the app icon sits on.
 *
 * Deliberately the same value as the mark's outer halo, so the halo vanishes
 * inside the icon and reappears the moment the mark is used anywhere else.
 * It is not pure black: a near-black carrying the palette's hue belongs to
 * the app, and pure black reads as a hole on a home screen.
 */
const TILE = MARK_COLORS.halo;

/**
 * The two faces the app uses, pinned to the exact files Google serves today.
 *
 * They are downloaded into a cache the repository ignores rather than
 * committed, because what this script produces — a PNG — is the thing worth
 * versioning. The renderer never sees them as fonts: text is converted to
 * outlines below, since librsvg, which sharp rasterises with, ignores an
 * embedded @font-face and would silently substitute whatever the machine
 * happens to have. A card that looks different on every machine is worse than
 * no card.
 */
const FONTS = {
  display: {
    file: "BricolageGrotesque-ExtraBold.ttf",
    url: "https://fonts.gstatic.com/s/bricolagegrotesque/v9/3y9U6as8bTXq_nANBjzKo3IeZx8z6up5BeSl5jBNz_19PpbpMXuECpwUxJBOm_OJWiaaD30YfKfjZZoLvZvlyM0.ttf",
  },
  body: {
    file: "PublicSans-Regular.ttf",
    url: "https://fonts.gstatic.com/s/publicsans/v21/ijwGs572Xtc6ZYQws9YVwllKVG8qX1oyOymuFpm5ww.ttf",
  },
};

const FONT_CACHE = join(process.cwd(), "scripts", ".fonts");

async function loadFont({ file, url }) {
  const path = join(FONT_CACHE, file);

  if (!existsSync(path)) {
    console.log("downloading", file);
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(
        `Could not download ${file} (HTTP ${response.status}). The card is ` +
          `only regenerated by hand, so this needs a connection — or drop ` +
          `the file into scripts/.fonts/ yourself.`
      );
    }
    await mkdir(FONT_CACHE, { recursive: true });
    await writeFile(path, Buffer.from(await response.arrayBuffer()));
  }

  const buffer = await readFile(path);
  return opentype.parse(
    buffer.buffer.slice(
      buffer.byteOffset,
      buffer.byteOffset + buffer.byteLength
    )
  );
}

/**
 * Walks a string glyph by glyph, applying kerning by hand.
 *
 * opentype.js's own getPath and getAdvanceWidth run the string through a
 * shaping engine that throws on this font's ccmp lookup ("Lookup type is not
 * yet supported"). Nothing here needs shaping — two short Latin lines with no
 * ligatures — so going straight to the glyphs avoids the whole path.
 */
function layout(font, text, size) {
  const scale = size / font.unitsPerEm;
  const glyphs = [];
  let width = 0;
  let previous = null;

  for (const character of text) {
    const glyph = font.charToGlyph(character);
    if (previous !== null)
      width += font.getKerningValue(previous, glyph) * scale;
    glyphs.push({ glyph, offset: width });
    width += glyph.advanceWidth * scale;
    previous = glyph;
  }

  return { glyphs, width };
}

/**
 * One line of text as outlines, so no font has to exist at render time.
 *
 * One <path> per glyph, not one for the whole line: librsvg stops reading a
 * `d` attribute somewhere past four thousand characters, which silently drew
 * the first eight letters of the tagline and dropped the rest. Per glyph, no
 * line comes anywhere near the limit.
 */
function textPath(font, text, x, y, size, fill, opacity = 1) {
  const { glyphs } = layout(font, text, size);
  const fillOpacity = opacity === 1 ? "" : ` fill-opacity="${opacity}"`;

  return glyphs
    .map(({ glyph, offset }) =>
      glyph.getPath(x + offset, y, size).toPathData(2)
    )
    .filter((d) => d.length > 0)
    .map((d) => `<path d="${d}" fill="${fill}"${fillOpacity}/>`)
    .join("");
}

const textWidth = (font, text, size) => layout(font, text, size).width;

/**
 * The mark itself, in its own 166x166 space.
 *
 * Everything here comes from src/lib/design/mark.mjs, which the Logo
 * component reads too, so the icon and the one in the header cannot drift.
 */
function markBody() {
  const { center: c } = MARK;
  return `<circle cx="${c}" cy="${c}" r="${haloOuterRadius}" fill="none" stroke="${MARK_COLORS.halo}" stroke-width="${MARK.haloOuter}"/>
  <circle cx="${c}" cy="${c}" r="${MARK.ringRadius}" fill="${MARK_COLORS.face}"/>
  <circle cx="${c}" cy="${c}" r="${MARK.ringRadius}" fill="none" stroke="${MARK_COLORS.track}" stroke-width="${MARK.ringWidth}"/>
  <path d="${arcPath()}" fill="none" stroke="${MARK_COLORS.arc}" stroke-width="${MARK.ringWidth}" stroke-linecap="butt"/>
  <circle cx="${c}" cy="${c}" r="${haloInnerRadius}" fill="none" stroke="${MARK_COLORS.halo}" stroke-width="${MARK.haloInner}"/>
  <rect x="${c - MARK.handWidth / 2}" y="${c - MARK.minuteHand}" width="${MARK.handWidth}" height="${MARK.minuteHand}" rx="${MARK.handWidth / 2}" fill="${MARK_COLORS.hands}"/>
  <rect x="${c - MARK.handWidth / 2}" y="${c - MARK.hourHand}" width="${MARK.handWidth}" height="${MARK.hourHand}" rx="${MARK.handWidth / 2}" fill="${MARK_COLORS.hands}" transform="rotate(${MARK.hourAngle} ${c} ${c})"/>
  <circle cx="${c}" cy="${c}" r="${MARK.pin}" fill="${MARK_COLORS.hands}"/>`;
}

/** The mark on its own, with nothing behind it. */
function bareMark() {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${MARK.size}" height="${MARK.size}" viewBox="0 0 ${MARK.size} ${MARK.size}">
  <title>REP Calc</title>
  ${markBody()}
</svg>`;
}

/**
 * The mark on the app's tile.
 *
 * `occupies` is how much of the tile the drawing takes. The outer halo is the
 * tile colour, so roughly a tenth of that is invisible padding — which is
 * why the visible clock lands where it should without a second margin.
 */
function tiledMark({ size = 512, occupies = 0.76, rounded = true }) {
  const inner = size * occupies;
  const offset = (size - inner) / 2;

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
  <title>REP Calc</title>
  <rect width="${size}" height="${size}"${rounded ? ` rx="${size * 0.22}"` : ""} fill="${TILE}"/>
  <g transform="translate(${offset} ${offset}) scale(${inner / MARK.size})">${markBody()}</g>
</svg>`;
}

const TARGETS = [
  // On its own: the browser tab, and anywhere the mark is used loose. The
  // halo is what gives it a contour against whatever it lands on.
  { file: "icon.svg", svg: bareMark() },
  { file: "icon-192.png", size: 192, svg: tiledMark({}) },
  { file: "icon-512.png", size: 512, svg: tiledMark({}) },
  // Maskable icons get cropped to a circle by some launchers, so the drawing
  // sits well inside the safe zone and the tile bleeds to the edges.
  {
    file: "icon-maskable-512.png",
    size: 512,
    svg: tiledMark({ occupies: 0.6, rounded: false }),
  },
  // iOS rounds this one itself, so it ships square.
  {
    file: "apple-touch-icon.png",
    size: 180,
    svg: tiledMark({ rounded: false }),
  },
];

await mkdir(OUT, { recursive: true });

for (const target of TARGETS) {
  const path = join(OUT, target.file);
  if (target.file.endsWith(".svg")) {
    await writeFile(path, target.svg, "utf8");
  } else {
    await sharp(Buffer.from(target.svg)).resize(target.size).png().toFile(path);
  }
  console.log("wrote", target.file);
}

/**
 * The card that stands in for the app when a link is shared.
 *
 * Drawn rather than screenshotted: a screenshot goes stale with every layout
 * change, and the one it replaced still showed the 2023 interface, a version
 * number two majors old, and a menu that no longer exists.
 *
 * 1200x630 is what LinkedIn, WhatsApp and Slack all read. Note that their
 * caches are aggressive — the first fetch after publishing is effectively the
 * one that sticks.
 */
async function ogCard() {
  const [display, body] = await Promise.all([
    loadFont(FONTS.display),
    loadFont(FONTS.body),
  ]);

  const W = 1200;
  const H = 630;
  const X = 96;
  // The text column stops here so it never runs into the mark on the right.
  const COLUMN = 700;

  const title = "REP Calc";
  const tagline = "Calculadora de horas para quem bate ponto";
  const url = "repcalc.leandrofaria.com";

  const titleSize = 116;
  const taglineSize = 34;
  const urlSize = 26;

  // Better to fail here than to ship a card with a word running under the
  // mark. The sizes above are chosen against this, not the other way round.
  const widest = Math.max(
    textWidth(display, title, titleSize),
    textWidth(body, tagline, taglineSize)
  );
  if (widest > COLUMN) {
    throw new Error(
      `Text overflows the column: ${Math.round(widest)}px of ${COLUMN}px.`
    );
  }

  // The mark at card scale, on the same ground as the app icon — so the halo
  // is invisible here too and a link preview looks like the installed app.
  const markSize = 300;
  const markX = 820;
  const markY = (H - markSize) / 2;

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
  <rect width="${W}" height="${H}" fill="${TILE}"/>
  <g transform="translate(${markX} ${markY}) scale(${markSize / MARK.size})">${markBody()}</g>
  ${textPath(display, title, X, 322, titleSize, ON_BRAND)}
  ${textPath(body, tagline, X, 382, taglineSize, ON_BRAND, 0.9)}
  ${textPath(body, url, X, 520, urlSize, ON_BRAND, 0.6)}
</svg>`;
}

await sharp(Buffer.from(await ogCard()))
  .png({ compressionLevel: 9 })
  .toFile(join(process.cwd(), "public", "og.png"));
console.log("wrote public/og.png");

// The browser tab icon and the iOS home-screen icon, by Next's file
// convention. Same source, so they cannot drift from the palette.
await writeFile(join(APP, "icon.svg"), bareMark(), "utf8");
await sharp(Buffer.from(tiledMark({ rounded: false })))
  .resize(180)
  .png()
  .toFile(join(APP, "apple-icon.png"));
console.log("wrote src/app/icon.svg and src/app/apple-icon.png");
